# Generated by Django 4.1.2 on 2022-11-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('video_information_id', models.IntegerField(blank=True, null=True)),
                ('video_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'video_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VideoInformation',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('video_name', models.CharField(blank=True, max_length=255, null=True)),
                ('video_url', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'video_information',
                'managed': False,
            },
        ),
    ]
